# References
#
#     https://docs.astral.sh/uv/guides/integration/github/
#     https://docs.astral.sh/uv/guides/publish/#preparing-your-project-for-packaging
#     https://docs.pypi.org/trusted-publishers/adding-a-publisher/
#

name: build-and-release

on:
  workflow_call:
    inputs:
      library_name:
        required: true
        type: string
      working_directory:
        required: true
        type: string
    secrets:
      pypi_token:
        required: true
jobs:
  build:
    name: python
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python
        working-directory: ${{ inputs.working_directory }}
        run: uv python install

      - name: Build
        working-directory: ${{ inputs.working_directory }}
        run: uv build

      - name: Validate release version
        run: python .github/validate-release-version.py ${{ inputs.working_directory }}/dist ${{ github.ref_name }}

      - name: Publish
        working-directory: ${{ inputs.working_directory }}
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.pypi_token }}