name: quality-check

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install python
        working-directory: ${{ inputs.working_directory }}
        run: uv python install 3.9

      - name: Sync dependencies
        working-directory: ${{ inputs.working_directory }}
        run: uv sync

      - name: Ruff (lint)
        working-directory: ${{ inputs.working_directory }}
        run: uv run ruff check

      - name: Ruff (formatting)
        working-directory: ${{ inputs.working_directory }}
        run: uv run ruff format --check .

      - name: Pyright
        working-directory: ${{ inputs.working_directory }}
        run: uv run pyright

      - name: Pytest
        working-directory: ${{ inputs.working_directory }}
        run: uv run pytest